#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
    ln -s /usr/lib/homedesk/homedesk /usr/bin/homedesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/homedesk.service ]; then
			rm /etc/systemd/system/homedesk.service /usr/lib/systemd/system/homedesk.service /usr/lib/systemd/user/homedesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/homedesk/files/systemd/homedesk.service /usr/lib/systemd/system/homedesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload homedesk.service: Unit homedesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/homedesk.service:10: Executable path is not absolute: pkill -f "homedesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/homedesk.service
		fi
		systemctl daemon-reload
		systemctl enable homedesk
		systemctl start homedesk
	fi
fi
